### PR TITLE
chore: use functions for query keys

### LINKED ISSUE #359: use functions to create svelte query keys
Currently, we use manually defined keys for `queryKey` in our svelte queries. We can use functions to create these keys and have a more robust and homogenised query key

### PR DESCRIPTION
**Pull request by Aslemammad**
Resolves #359

### CODE REVIEW

**Comment by gzuuus** [comment]
Perfect! This is the approach I was imagining. Now we just need to implement it for all the queries

**Comment by gzuuus** [comment]
great! i think that to finish the pr we should also use this new functions for query keys for invalidation, right now all invalidations stills using manual query keys `queryClient.invalidateQueries({ queryKey: ['orders'] })`

**Review by gzuuus — CHANGES_REQUESTED** [review]
use this functions to invalidate queries

**Comment by Aslemammad** [comment]
will deal with it soon!

**Comment by gzuuus** [comment]
Ill finish this 👌

**Pull request merged**
